apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-travix-test
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: web
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000