apiVersion: v1
kind: Service
metadata:
  name: travix-test-service
  namespace: travix-dev
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31704