replicaCount: 2

namespace: travix-dev

image:
  repository: allloush92/travix_test
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 31704
  protocol: TCP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
